services:
 telemetry-dashboard:
  image: mcr.microsoft.com/dotnet/aspire-dashboard:9.1
  ports:
   - "4317:18889"
   - "18888:18888"
  environment:
   - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

