services:
 telemetry-dashboard:
  image: mcr.microsoft.com/dotnet/aspire-dashboard:9.1
  ports:
   - "4317:18889"
   - "18888:18888"
  environment:
   - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317

 postgresDb:
  image: postgres:17
  ports:
   - "5432:5432"
  environment:
   - POSTGRES_PASSWORD=mysecretpassword
   - POSTGRES_DB=MyCleanArchTemplateDB
  volumes:
   - postgres-data:/var/lib/postgresql/data

volumes:
 postgres-data:



