services:
 aspire-dashboard:
  image: mcr.microsoft.com/dotnet/aspire-dashboard:9.1
  container_name: aspire-dashboard
  ports:
   - "4317:18889"
   - "18888:18888"
  environment:
   - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
  profiles:
    - aspire 

 otel-lgtm:
    image: grafana/otel-lgtm:0.11.1
    container_name: otel-lgtm
    ports:
        - "3000:3000"
        - "4317:4317"
        - "4318:4318"
    volumes:
        - otel-lgtm-telemetry:/data
    profiles:
        - lgtm

 postgres:
  image: postgres:17
  container_name: postgres
  ports:
   - "5432:5432"
  environment:
   - POSTGRES_PASSWORD=mysecretpassword
   - POSTGRES_DB=MyCleanArchTemplateDB
  volumes:
   - postgres-data:/var/lib/postgresql/data

 kafka:
   image: confluentinc/confluent-local:7.9.1
   container_name: kafka
   volumes:
     - kafka-data:/tmp/kraft-combined-logs
     - kafka-secrets:/etc/kafka/secrets
   ports:
     - "9092:9092"
     - "9093:9093"

 redis-stack:
   image: redis/redis-stack:7.4.0-v3
   container_name: redis-stack
   ports:
    - "6379:6379"
    - "8001:8001"

volumes:
 postgres-data:
 kafka-data:
 kafka-secrets:
 otel-lgtm-telemetry:


